# Generated by Django 3.1.7 on 2021-03-07 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vakcinisani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vakcinisan',
            name='vakcina',
            field=models.CharField(choices=[('fajzer', 'fajzer'), ('sputnjk', 'sputnjik'), ('astra zeneka', 'astra zeneka'), ('sinofarm', 'sinofarm'), ('moderna', 'moderna')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
