# Generated by Django 3.1.7 on 2021-03-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakcinisani', '0004_auto_20210311_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='vakcinisan',
            name='alergija',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vakcinisan',
            name='datum',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vakcinisan',
            name='jmbg',
            field=models.IntegerField(default=123456789),
        ),
    ]
