# Generated by Django 3.1.7 on 2021-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakcinisani', '0007_auto_20210322_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakcinisan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
