# Generated by Django 3.1.7 on 2021-03-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakcinisani', '0008_auto_20210322_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakcinisan',
            name='jmbg',
            field=models.CharField(max_length=13),
        ),
    ]
