# Generated by Django 3.1.7 on 2021-03-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakcinisani', '0010_auto_20210327_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='vakcinisan',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
