# Generated by Django 3.1.7 on 2021-03-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakcinisani', '0011_vakcinisan_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vakcinisan',
            old_name='email',
            new_name='email_1',
        ),
        migrations.AddField(
            model_name='vakcinisan',
            name='email_2',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
