# Generated by Django 3.1.7 on 2021-04-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vakcinisani', '0012_auto_20210329_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ime_bolesti', models.CharField(max_length=100)),
                ('datum_dijagnostike', models.DateTimeField()),
                ('vakcinisani_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vakcinisani.vakcinisan')),
            ],
        ),
    ]
