# Generated by Django 3.1.7 on 2021-04-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakcinisani', '0013_bolest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolest',
            name='datum_dijagnostike',
            field=models.DateField(),
        ),
    ]
