# Generated by Django 3.1.7 on 2021-04-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vakcinisani', '0014_auto_20210417_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolest',
            name='vakcinisani_id',
        ),
    ]
