# Generated by Django 3.1.7 on 2021-04-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vakcinisani', '0015_remove_bolest_vakcinisani_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vakcinisan',
            name='bolest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vakcinisani.bolest'),
        ),
    ]
