# Generated by Django 3.1.7 on 2021-04-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vakcinisani', '0016_vakcinisan_bolest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolest',
            name='datum_dijagnostike',
        ),
        migrations.AddField(
            model_name='bolest',
            name='ime_doktora',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
