# Generated by Django 3.1.7 on 2021-05-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vakcinisani', '0017_auto_20210417_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakcinisan',
            name='bolest_id',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vakcinisani.bolest'),
        ),
    ]
